### PR TITLE
Fix semver and errors on bundling

### LINKED ISSUE #13: Can't install package via npm
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ottisk-crm-frontend@0.0.0
npm ERR! Found: effector@22.8.8
npm ERR! node_modules/effector
npm ERR!   effector@"^22.8.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer effector@"^22 | ^23" from effector-factorio@1.2.0
npm ERR! node_modules/effector-factorio
npm ERR!   effector-factorio@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\konin.mv\AppData\Local\npm-cache\_logs\2023-12-12T10_26_39_333Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\konin.mv\AppData\Local\npm-cache\_logs\2023-12-12T10_26_39_333Z-debug-0.log
```

### PR DESCRIPTION
**Pull request by KoninMikhail**
Closes Kelin2025/effector-factorio#13

### CODE REVIEW

**Comment by gormonn** [comment]
When I try to install the version from your PR I get the following errors:
```bash
npm install git+https://github.com/KoninMikhail/effector-factorio.git#patch-1
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/dmitriychernukho/.nvm/versions/node/v20.9.0/bin/node /Users/dmitriychernukho/.nvm/versions/node/v20.9.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/dmitriychernukho/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > effector-factorio@1.2.0 prepare
npm ERR! > npm run build
npm ERR! 
npm ERR! 
npm ERR! > effector-factorio@1.2.0 build
npm ERR! > rollup -c rollup.config.js
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm ERR! npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm ERR! npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! 
npm ERR! src/index.tsx → dist/cjs/index.js, dist/esm/index.js...
npm ERR! babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
npm ERR! created dist/cjs/index.js, dist/esm/index.js in 399ms
npm ERR! 
npm ERR! src/solid.tsx → dist/cjs/solid.js, dist/esm/solid.js...
npm ERR! babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
npm ERR! created dist/cjs/solid.js, dist/esm/solid.js in 94ms
npm ERR! 
npm ERR! src/index.tsx → dist/index.d.ts...
npm ERR! created dist/index.d.ts in 1.8s
npm ERR! 
npm ERR! src/solid.tsx → dist/solid.d.ts...
npm ERR! src/solid.tsx(2,32): error TS2307: Cannot find module 'solid-js' or its corresponding type declarations.
npm ERR! src/solid.tsx(3,43): error TS2307: Cannot find module 'solid-js' or its corresponding type declarations.
npm ERR! src/solid.tsx(4,25): error TS2307: Cannot find module 'solid-js/web' or its corresponding type declarations.
npm ERR! src/solid.tsx(58,7): error TS2307: Cannot find module 'solid-js/jsx-runtime' or its corresponding type declarations.
npm ERR! src/solid.tsx(58,32): error TS18046: 'props' is of type 'unknown'.
npm ERR! src/solid.tsx(59,39): error TS2698: Spread types may only be created from object types.
npm ERR! 
npm ERR! [!] (plugin dts) Error: Failed to compile. Check the logs above.
npm ERR! src/solid.tsx
npm ERR! Error: Failed to compile. Check the logs above.
npm ERR!     at error (/Users/dmitriychernukho/.npm/_cacache/tmp/git-cloneVKTRNp/node_modules/rollup/dist/shared/rollup.js:198:30)
npm ERR!     at throwPluginError (/Users/dmitriychernukho/.npm/_cacache/tmp/git-cloneVKTRNp/node_modules/rollup/dist/shared/rollup.js:21718:12)
npm ERR!     at Object.error (/Users/dmitriychernukho/.npm/_cacache/tmp/git-cloneVKTRNp/node_modules/rollup/dist/shared/rollup.js:22672:20)
npm ERR!     at Object.error (/Users/dmitriychernukho/.npm/_cacache/tmp/git-cloneVKTRNp/node_modules/rollup/dist/shared/rollup.js:21895:42)
npm ERR!     at Object.transform (/Users/dmitriychernukho/.npm/_cacache/tmp/git-cloneVKTRNp/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1644:26)
npm ERR!     at /Users/dmitriychernukho/.npm/_cacache/tmp/git-cloneVKTRNp/node_modules/rollup/dist/shared/rollup.js:22879:40
npm ERR! 
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/dmitriychernukho/.npm/_cacache/tmp/git-cloneVKTRNp
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npm run build
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in: /Users/dmitriychernukho/.npm/_logs/2023-12-14T00_58_03_987Z-debug-0.log

npm ERR! A complete log of this run can be found in: /Users/dmitriychernukho/.npm/_logs/2023-12-14T00_56_51_065Z-debug-0.log

```

**Comment by KoninMikhail** [comment]
OK. my fix was only in the package.json syntax, but I think the problem is deeper, I need to understand further. However, from your log I see other errors.

**Comment by KoninMikhail** [comment]
I've fixed this problem. try again )))

**Comment by KoninMikhail** [comment]
`npm install git+https://github.com/KoninMikhail/effector-factorio.git#patch-1` for install

**Comment by SQReder** [comment]
bump this

**Pull request merged**
